<?php
return [
    'Yürüyüş (5 km/saat)' => 3.3,
    'Tempolu Yürüyüş (8 km/saat)' => 8.3,
    'Koşu (10 km/saat)' => 10,
    'Bisiklet (hafif, 16 km/saat)' => 6,
    'Bisiklet (orta, 20 km/saat)' => 8,
    'Bisiklet (hızlı, 22-25 km/saat)' => 10.0,
    'Yüzme (orta tempolu)' => 6,
    'Yüzme (süratli)' => 10,
    'Tenis' => 5,
    'Basketbol' => 8,
    'Futbol (orta tempolu)' => 7,
    'Yoga' => 2.5,
    'Pilates' => 3,
    'Jimnastik' => 3,
    'Ağırlık kaldırma (hafif)' => 3.0,
    'Ağırlık kaldırma (orta)' => 6.0,
    'Ağırlık kaldırma (ağır)' => 8.0,
    'Kayak (kros, orta tempolu)' => 7,
    'Merdiven çıkma' => 8.0,
    'Dans (orta tempolu)' => 5.0,
    'Dans (hızlı tempolu)' => 7.8,
];
